### ISSUE TITLE
[VERSION] 1.21 Version Port Request

### ISSUE THREAD

**Issue by WatermelonFroggy** [rotgruengelb/hopperpots#2]
### Minecraft Version

1.21

### Affected Mod loader

Fabric

### Checklist

- [X] I have checked that the requested version is not in the repository, including all branches.
- [X] I have checked that the requested version was not already requested, including closed issues.
- [X] I have filled out all blanks in the Request Template, including the blank in the Tite!
- [ ] I have clicked these checkboxes without reading them.
- [X] I have checked that the requested version is not already being publicly worked on.
- [X] I have checked that the requested version is not available on the Projects Distribution Pages (example: Modrinth).

**Comment by rotgruengelb** [comment]
Will work on it. Thanks for the request!

**Comment by rotgruengelb** [comment]
@WatermelonFroggy Updated to 1.21. New Version on Modrinth. ;D

**Comment by rotgruengelb** [comment]
https://modrinth.com/mod/hopperpots/version/1.0.0+1.21
